service: cv-19-food-delivery
provider:
  name: aws
  runtime: dotnetcore2.1

  stage: dev
  region: eu-west-2
package:
  individually: true

functions:
  getHelpRequests-v1:
    handler: CsharpHandlers::CV19INeedHelp.Handler::GetHelpRequests
    package:
      artifact: bin/release/netcoreapp2.1/cv-19-i-need-help.zip
    events:
      - http:
          path: help-requests
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false