service: cv-19-food-delivery
provider:
  name: aws
  runtime: dotnetcore2.1

  stage: dev
  region: eu-west-2
package:
  individually: true

functions:
  getHelpRequests-v1:
    handler: CsharpHandlers::CV19INeedHelp.Handler::GetHelpRequests
    package:
      artifact: bin/release/netcoreapp2.1/cv-19-i-need-help.zip
    events:
      - http:
          path: help-requests
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  getHelpRequest-v1:
    handler: CsharpHandlers::CV19INeedHelp.Handler::GetHelpRequest
    package:
      artifact: bin/release/netcoreapp2.1/cv-19-i-need-help.zip
    events:
      - http:
          path: help-requests/{id}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false 
  updateHelpRequest-v1:
    handler: CsharpHandlers::CV19INeedHelp.Handler::UpdateHelpRequest
    package:
      artifact: bin/release/netcoreapp2.1/cv-19-i-need-help.zip
    events:
      - http:
          path: help-requests/{id}
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  patchHelpRequest-v1:
    handler: CsharpHandlers::CV19INeedHelp.Handler::PatchHelpRequest
    package:
      artifact: bin/release/netcoreapp2.1/cv-19-i-need-help.zip
    events:
      - http:
          path: help-requests/{id}
          method: patch
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  getFoodDeliveryRequestsForForm-v1:
    handler: CsharpHandlers::CV19INeedHelp.Handler::GetFoodDeliveriesRequestForForm
    package:
      artifact: bin/release/netcoreapp2.1/cv-19-i-need-help.zip
    events:
      - http:
          path: help-requests/{id}/food-deliveries
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false        
  createFoodDeliveryRequest-v1:
    handler: CsharpHandlers::CV19INeedHelp.Handler::CreateFoodDeliveryRequest
    package:
      artifact: bin/release/netcoreapp2.1/cv-19-i-need-help.zip
    events:
      - http:
          path: help-requests/{id}/food-deliveries
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  updateFoodDeliveryRequest-v1:
    handler: CsharpHandlers::CV19INeedHelp.Handler::UpdateFoodDeliveryRequest
    package:
      artifact: bin/release/netcoreapp2.1/cv-19-i-need-help.zip
    events:
      - http:
          path: help-requests/{id}/food-deliveries
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false