version: 2.1

jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: cv-19-i-need-help
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: cv-19-i-need-help
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: cv-19-i-need-help-test